services:
  cerbos:
    image: ghcr.io/cerbos/cerbos:0.36.0
    ports:
      - "3592:3592"
      - "3593:3593"
    volumes:
      - "../policy:/policies"
      - "./config/cerbos.yaml:/config/cerbos.yaml"
    command: [server, --config=config/cerbos.yaml]

  zitadel:
    restart: "always"
    networks:
      - dev
    image: "ghcr.io/zitadel/zitadel:latest"
    command:
      [
        start-from-init,
        --masterkey,
        MasterkeyNeedsToHave32Characters,
        --tlsMode,
        disabled,
        --config,
        /mnt/config/zitadel.yaml,
      ]
    environment:
      - "ZITADEL_EXTERNALSECURE=false"
    volumes:
      - "./config/zitadel.yaml:/mnt/config/zitadel.yaml"
    depends_on:
      db:
        condition: "service_healthy"
    ports:
      - "8080:8080"

  db:
    restart: "always"
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zitadel
    networks:
      - dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    ports:
      - "5432:5432"

networks:
  dev:
